version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: cristiansto
      POSTGRES_PASSWORD: Soccer@dockerdatabase
      POSTGRES_DB: Soccer
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
